### PR TITLE
upgrade to Symfony 6.3

### PR DESCRIPTION
**Pull request by hbagherzadegan**
### please **Don't Merge this** until all Service ready for symfony  6.3

### CODE REVIEW

**Comment by JarJak** [comment]
This repo is not actively maintained and probably unused.

**Comment by hbagherzadegan** [comment]
> This repo is not actively maintained and probably unused.

in this way it's better to archive it and nobody should need it for clone it any more ,what's your idea @leopcastro

**Comment by leopcastro** [comment]
Currently we use it in the newest services to merge our openapi files into one. Just one not so good thing, is that we don't use `main` branch, but `dev-read-dir-end-disable-reference-check`. 

Also I think Jarek updated it to php 8.2 in branch `read-dir-end-disable-reference-check-php82`, so if there is still something to update, it should be done based on that branch. 

We need to think later if it makes sense to merge it to main, or something like that.

**Comment by JarJak** [comment]
Yes I have found out that it is used, but not the `main` branch, which should stay in sync with the forked repo

**Pull request closed without merging**
